#!/usr/bin/env python3
# Credit: https://raw.githubusercontent.com/dizzythinks/asg_persistence/12ec0550534adf7531d7837c87672df400519df5/attach_volume.py
# Revisions:
# 2021-11-28: Patched by github.com/zph to work with Python3
"""Retrieve available EBS volume in AZ."""

import sys
import os
import boto3
import argparse
import time
import urllib3


def parse_args():
    """Argument needs to be parsed."""
    parser = argparse.ArgumentParser(description='Attach EBS Volume')
    parser.add_argument('--tag', action='store', default='Name',
                        help='Tag key, defaults to Name')
    parser.add_argument('--value', action='store', required=True,
                        help='The tag value to search for')
    parser.add_argument('--attach-as', action='store', required=True,
                        help='device path e.g. /dev/xvdb')
    parser.add_argument('--skip_check', action='store', required=False,
                        help='skip the check and just continue')
    parser.add_argument('--wait', action='store_true', required=False,
                        help='If no available volume is found, wait.')
    return parser.parse_args()


http = urllib3.PoolManager()

def utils(endpoint):
    """Replacing boto.utils, read from instance metadata directly."""

    url = 'http://169.254.169.254/latest/meta-data/%s' % endpoint
    resp = http.request('GET', url)
    return resp.data.decode("utf-8")


def instance_id():
    """Retrieve current Instance's ID."""
    return utils('instance-id')


def region():
    """Retrieve current Instance's Region."""
    return zone()[:-1]


def zone():
    """Retrieve current Instance's Zone."""
    return utils('placement/availability-zone')


def filters(tag, val):
    """Helper method for parsing filters."""
    return {
        'Name': 'tag:%s' % tag,
        'Values': ['%s' % val]
    }


def find(tag, val, client=None):
    """Locate a free volume for this instance."""
    c = client or boto3.client('ec2', region())
    try:
        for x in c.describe_volumes(Filters=[filters(tag, val)])['Volumes']:
            if x['AvailabilityZone'] == zone():
                if x['State'] == 'available':
                    return x
    except(Exception, e):
        print(e)
        sys.exit(2)


def attach(vol_id, attach_as, client=None):
    """Attach EBS volume to an Instance."""
    c = client or boto3.client('ec2', region())
    if not vol_id:
        raise Exception('No volumes available')
        sys.exit(4)

    try:
        c.attach_volume(
            VolumeId=vol_id,
            InstanceId=instance_id(),
            Device=attach_as)
    except(Exception, e):
        print(e)
        sys.exit(3)


def already_attached(args):
    """Check if the disk is actually already attached."""
    ec2 = boto3.resource('ec2', region())
    instance = ec2.Instance(instance_id())
    for v in instance.volumes.all():
        volume = ec2.Volume(v.id)
        if volume.tags:
            for tag in volume.tags:
                if tag['Key'] == args.tag and tag['Value'] == args.value:
                    print('Disk is attached!')


def main(args):
    """Initialize find+attach action."""
    already_attached(args)

    client = boto3.client('ec2', region())
    volume_id = None
    volume = find(args.tag, args.value, client)
    if volume:
        volume_id = volume['VolumeId']
        if volume['State'] != 'available' and args.wait:
            volume_waiter = client.get_waiter('volume_available')
            volume_waiter.wait(VolumeIds=[volume_id])

    print(f"Attaching {volume_id} at {args.attach_as}".)
    attach(volume_id, args.attach_as, client)

    if not args.skip_check:
        counter = 0
        print("Checking for disk attachment")
        while not already_attached(args):
            counter = counter + 5
            time.sleep(5)
            if counter > 600:
                raise Exception('Timeout waiting for attachment')
                sys.exit(2)

    print("Attachment complete")

if __name__ == "__main__":
    main(parse_args())
